//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicationForTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resurce
    {
        public int idResurce { get; set; }
        public string TaskPicture { get; set; }
    }
}
