//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicationForTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsResulst
    {
        public int StudentResultsId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Scores { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<System.DateTime> DataTest { get; set; }
        public string TestName { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
